load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "args_parser",
    srcs = ["args_parser.cpp", "args_parser.hpp", "args_exception.h"],
)
