#ifndef HORCRUX_MAIN_UTILS_INCLUDE_CONSTANTS_HPP
#define HORCRUX_MAIN_UTILS_INCLUDE_CONSTANTS_HPP

namespace horcrux
{
	constexpr uint8_t KEY_SIZE = 32;
}

#endif //HORCRUX_MAIN_UTILS_INCLUDE_CONSTANTS_HPP
